version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_prod
    ports:
      - "4000:4000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    command: npm run start
    restart: always

  db:
    image: postgres:15
    container_name: postgres_prod
    environment:
      POSTGRES_DB: gym_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:


#Command to run the production environment
# docker-compose -f docker-compose.prod.yaml up --build -d
