-- AlterTable
ALTER TABLE "Trainee" ADD COLUMN     "bmi" DOUBLE PRECISION,
ADD COLUMN     "bodyFatPercentage" DOUBLE PRECISION,
ADD COLUMN     "height" DOUBLE PRECISION,
ADD COLUMN     "weight" DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Trainer" ADD COLUMN     "bmi" DOUBLE PRECISION,
ADD COLUMN     "bodyFatPercentage" DOUBLE PRECISION,
ADD COLUMN     "height" DOUBLE PRECISION,
ADD COLUMN     "weight" DOUBLE PRECISION;
